apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
            - containerPort: 22
          env:
            - name: APP_NAME
              value: "Gitea: Git with a cup of tea"
            - name: DB_TYPE
              value: "sqlite3"
            - name: RUN_MODE
              value: "prod"
          volumeMounts:
            - name: gitea-data
              mountPath: /data
      volumes:
        - name: gitea-data
          emptyDir: {}